=== chrismcdev/small-distance-courier-service/src/assets/estimate-delivery-time-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Estimate Delivery Time Input",
  "type": "object",
  "required": [
    "baseDeliveryCost",
    "noOfVehicles",
    "maxSpeed",
    "maxCarriableWeight",
    "parcels"
  ],
  "properties": {
    "baseDeliveryCost": {
      "$id": "#root/baseDeliveryCost",
      "title": "Base Delivery Cost",
      "type": "integer",
      "examples": [100],
      "default": 0
    },
    "noOfVehicles": {
      "$id": "#root/noOfVehicles",
      "title": "Number of Vehicles",
      "type": "integer",
      "examples": [2],
      "default": 0
    },
    "maxSpeed": {
      "$id": "#root/maxSpeed",
      "title": "Maximum Speed",
      "type": "integer",
      "examples": [70],
      "default": 0
    },
    "maxCarriableWeight": {
      "$id": "#root/maxCarriableWeight",
      "title": "Maximum Carriable Weight",
      "type": "integer",
      "examples": [200],
      "default": 0
    },
    "parcels": {
      "$id": "#root/parcels",
      "title": "Parcels",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/parcels/items",
        "title": "Items",
        "type": "object",
        "required": ["id", "weight", "distance", "couponCode"],
        "properties": {
          "id": {
            "$id": "#root/parcels/items/id",
            "title": "Parcel ID",
            "type": "string",
            "examples": ["PKG1"],
            "default": ""
          },
          "weight": {
            "$id": "#root/parcels/items/weight",
            "title": "Parcel Weight in Kilograms",
            "type": "integer",
            "examples": [50],
            "default": 0
          },
          "distance": {
            "$id": "#root/parcels/items/distance",
            "title": "Parcel Distance in Kilometers",
            "type": "integer",
            "examples": [30],
            "default": 0
          },
          "couponCode": {
            "$id": "#root/parcels/items/couponCode",
            "title": "Coupon Code",
            "type": "string",
            "examples": ["OFR001"],
            "default": ""
          }
        }
      }
    }
  }
}

=== chrismcdev/small-distance-courier-service/test/__mocks__/fetch-delivery-time-input.json
{
  "$schema": "../../src/assets/estimate-delivery-time-schema.json",
  "baseDeliveryCost": 100,
  "noOfVehicles": 2,
  "maxSpeed": 70,
  "maxCarriableWeight": 200,
  "parcels": [
    {
      "id": "PKG1",
      "weight": 50,
      "distance": 30,
      "couponCode": "OFR001"
    },
    {
      "id": "PKG2",
      "weight": 75,
      "distance": 125,
      "couponCode": "OFR008"
    },
    {
      "id": "PKG3",
      "weight": 175,
      "distance": 100,
      "couponCode": "OFR003"
    },
    {
      "id": "PKG4",
      "weight": 110,
      "distance": 60,
      "couponCode": "OFR002"
    },
    {
      "id": "PKG5",
      "weight": 155,
      "distance": 95,
      "couponCode": "NA"
    }
  ]
}
